import AppKit
import UniformTypeIdentifiers

/// Polls NSPasteboard.general every 0.75 s for new user-generated content.
/// Call suppress(for:) before any PunctoDock-internal clipboard write so those
/// changes are not recorded in the history.
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    var onNewText:  ((String) -> Void)?
    var onNewImage: ((Data, String) -> Void)?   // (imageData, pasteboardTypeRawValue)

    /// Image representations we recognise on the pasteboard, richest / most portable
    /// first. macOS usually synthesises `.tiff` for any image, so the first two catch
    /// almost everything; the rest cover apps that publish only one specific format.
    private static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png, .tiff,
        NSPasteboard.PasteboardType(UTType.jpeg.identifier),
        NSPasteboard.PasteboardType(UTType.gif.identifier),
        NSPasteboard.PasteboardType(UTType.heic.identifier),
        NSPasteboard.PasteboardType(UTType.heif.identifier),
        NSPasteboard.PasteboardType(UTType.bmp.identifier),
        NSPasteboard.PasteboardType(UTType.webP.identifier)
    ]

    /// De-facto privacy markers (see nspasteboard.com) that password managers and other
    /// sensitive sources set so clipboard managers skip the content. We honour them:
    /// passwords copied from 1Password/Keychain etc. are never recorded.
    private static let sensitiveMarkers: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    private var suppressUntil: Date = .distantPast

    private init() {}

    func start() {
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.75, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func suppress(for duration: TimeInterval = 1.0) {
        suppressUntil = Date().addingTimeInterval(duration)
    }

    private func poll() {
        let pb    = NSPasteboard.general
        let count = pb.changeCount
        defer { lastChangeCount = count }           // always track, even when suppressed
        guard count != lastChangeCount else { return }
        guard Date() >= suppressUntil  else { return }

        // Never record content flagged sensitive/transient by its source.
        if let types = pb.types, !Self.sensitiveMarkers.isDisjoint(with: Set(types)) { return }

        // ── Image data is checked BEFORE plain text. ───────────────────────────────
        // Browsers (Safari, Chrome, …) put both the image pixels AND the image URL as
        // plain text on the pasteboard when the user selects "Copy Image". The old
        // ordering let the text check win, recording the URL string instead of the
        // actual image. Images from any source (screenshots, browser copy, design
        // tools) now always take priority over any coincidental text on the pasteboard.

        // 1. Inline pixel data — screenshots, browser "Copy Image", design apps.
        if let item = pb.pasteboardItems?.first {
            for type in Self.imageTypes {
                if let data = item.data(forType: type) {
                    onNewImage?(data, type.rawValue)
                    return
                }
            }
        }

        // 2. Image FILE copied from Finder — arrives as a local file URL.
        //    Only local file:// URLs are considered; http/https image links are ignored.
        if let (data, type) = imageFromFileURL(on: pb) {
            onNewImage?(data, type.rawValue)
            return
        }

        // 3. Plain text — reached only when there is no image representation at all.
        if let text = pb.string(forType: .string), !text.isEmpty {
            onNewText?(text)
        }
    }

    /// If the pasteboard holds a single image file reference, returns its bytes and the
    /// pasteboard type matching the file's format.
    ///
    /// File-size is checked BEFORE loading to avoid reading multi-hundred-MB files
    /// (e.g. RAW photos or screenshots) into memory on the main thread. Files larger
    /// than ClipboardHistory.maxBytes are silently skipped — they would be rejected
    /// downstream anyway.
    private func imageFromFileURL(on pb: NSPasteboard) -> (Data, NSPasteboard.PasteboardType)? {
        guard let urls = pb.readObjects(forClasses: [NSURL.self],
                                        options: [.urlReadingFileURLsOnly: true]) as? [URL],
              let url = urls.first,
              let utType = UTType(filenameExtension: url.pathExtension),
              utType.conforms(to: .image)
        else { return nil }

        // Bail out early for oversized files — avoids reading e.g. a 200 MB RAW photo
        // synchronously on the main thread just to discard it a moment later.
        if let attrs = try? url.resourceValues(forKeys: [.fileSizeKey]),
           let fileSize = attrs.fileSize,
           fileSize > ClipboardHistory.maxBytes { return nil }

        guard let data = try? Data(contentsOf: url) else { return nil }
        return (data, NSPasteboard.PasteboardType(utType.identifier))
    }
}
